### ISSUE TITLE
Project name is "" in cases where trigger based on included artifact and artifact is a ci.yaml file. 

### ISSUE THREAD

**Issue by mercury200Hg** [catouc/gitlab-ci-crawler#98]
If a project uses ci.yml produced as an artifact then the relationship of the trigger should be the source project of the artifact but instead it's currently marked as ""

Steps to reproduce:

If your `.gitlab-ci.yml` contains following syntax:
````yaml
trigger:
    include:
      - artifact: child-ci.yml
        job: my-job
````

In that scenario the name of project in relationship is marked "" whereas it should either be should be the source project of the artifact.
